AlexNet:
  num_classes: 20
  init_weights: False

vgg:
  num_classes: 20
  init_weights: False
  model_name: 'vgg16'

GoogLeNet:
  num_classes: 20
  aux_logits: True
  init_weights: False

resnet34:
  num_classes: 20
  include_top: True

resnet50:
  num_classes: 20
  include_top: True

SqueezeNet:
  version: '1_0'
  num_classes: 20

train:
  seed: 42
  batch_size: 32
  epochs: 50

Inception3:
  num_classes: 20
  aux_logits: True

InceptionResNetV2:
  num_classes: 20

wideresnet40:
  num_classes: 20