AlexNet:
  num_classes: 20
  init_weights: False

vgg:
  num_classes: 20
  init_weights: False
  model_name: 'vgg16'

GoogLeNet:
  num_classes: 20
  aux_logits: True
  init_weights: False

resnet34:
  num_classes: 20
  include_top: True

resnet50:
  num_classes: 20
  include_top: True

SqueezeNet:
  version: '1_0'
  num_classes: 20

Inception3:
  num_classes: 20
  aux_logits: True

InceptionResNetV2:
  num_classes: 20

wideresnet40:
  num_classes: 20

wide_resnet50_2:
  num_classes: 20
  include_top: True
  width_per_group: 128

wide_resnet50_2_v2:
  num_classes: 20
  include_top: True
  width_per_group: 128

wide_resnet34_2_v2:
  num_classes: 20
  include_top: True
  width_per_group: 128

densenet121:
  num_classes: 20

densenet161:
  num_classes: 20

densenet169:
  num_classes: 20

densenet201:
  num_classes: 20

Xception:
  num_classes: 20

resnext50_32x4d:
  num_classes: 20
  include_top: True
  groups: 32
  width_per_group: 4

train:
  seed: 42
  batch_size: 32
  epochs: 50
